
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bentil
 */
public class Home extends javax.swing.JFrame {
    public int z = 0;
//    INITIALIZE MODULES
    NewCustomer newcustomer = new NewCustomer();
    UpdateCustomer updatecustomer = new UpdateCustomer();
    CustomerDetails customerdetails = new CustomerDetails();
    DeleteCustomer deletecustomer = new DeleteCustomer();
    NewProduct newproduct = new NewProduct();
    UpdateProduct updateproduct = new UpdateProduct();
    ProductDetails productdetails = new ProductDetails();
    DeleteProduct deleteproduct = new DeleteProduct();
    Sales sales = new Sales();
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        newCustomerBtn.setVisible(false);
        updateCustomerBtn.setVisible(false);
        customerDetailsBtn.setVisible(false);
        deleteCustomerBtn.setVisible(false);
        newProductBtn.setVisible(false);
        updateProductBtn.setVisible(false);
        productDetailsbtn.setVisible(false);
        deleteProductBtn.setVisible(false);
        salesBtn.setVisible(false);
        logoutBtn.setVisible(false);
        closeBtn.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        newCustomerBtn = new javax.swing.JButton();
        updateCustomerBtn = new javax.swing.JButton();
        customerDetailsBtn = new javax.swing.JButton();
        deleteCustomerBtn = new javax.swing.JButton();
        newProductBtn = new javax.swing.JButton();
        updateProductBtn = new javax.swing.JButton();
        productDetailsbtn = new javax.swing.JButton();
        deleteProductBtn = new javax.swing.JButton();
        salesBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 73, -1));

        newCustomerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        newCustomerBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newCustomerBtnComponentShown(evt);
            }
        });
        newCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 35, 73, -1));

        updateCustomerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        updateCustomerBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updateCustomerBtnComponentShown(evt);
            }
        });
        updateCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 35, 73, -1));

        customerDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer Details.png"))); // NOI18N
        customerDetailsBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                customerDetailsBtnComponentShown(evt);
            }
        });
        customerDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDetailsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 35, 73, -1));

        deleteCustomerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyer.png"))); // NOI18N
        deleteCustomerBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteCustomerBtnComponentShown(evt);
            }
        });
        deleteCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 35, 73, -1));

        newProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        newProductBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newProductBtnComponentShown(evt);
            }
        });
        newProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 35, 73, -1));

        updateProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        updateProductBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updateProductBtnComponentShown(evt);
            }
        });
        updateProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 35, 73, -1));

        productDetailsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details product.png"))); // NOI18N
        productDetailsbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                productDetailsbtnComponentShown(evt);
            }
        });
        productDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(productDetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 35, 73, -1));

        deleteProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete product.png"))); // NOI18N
        deleteProductBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteProductBtnComponentShown(evt);
            }
        });
        deleteProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 35, 73, -1));

        salesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        salesBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                salesBtnComponentShown(evt);
            }
        });
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 35, 79, -1));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logoutBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutBtnComponentShown(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 35, 79, -1));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        closeBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                closeBtnComponentShown(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1189, 35, 79, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Customer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 115, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Product");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 115, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update Product");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 115, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 115, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Delete Product");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 115, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sales");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1016, 115, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logout");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 115, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Close Application");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1176, 115, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.PNG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 2240, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerBtnActionPerformed
        // TODO add your handling code here:
        newcustomer.setVisible(true);
    }//GEN-LAST:event_newCustomerBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
                int a = JOptionPane.showConfirmDialog(null, "Do you want to close Aplication?", "Close App", JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(z == 0)
        {
            try{
                Thread.sleep(250);
                newCustomerBtn.setVisible(true);
                jLabel1.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        else
        {
            newCustomerBtn.setVisible(false);
            updateCustomerBtn.setVisible(false);
            customerDetailsBtn.setVisible(false);
            deleteCustomerBtn.setVisible(false);
            newProductBtn.setVisible(false);
            updateProductBtn.setVisible(false);
            productDetailsbtn.setVisible(false);
            deleteProductBtn.setVisible(false);
            salesBtn.setVisible(false);
            logoutBtn.setVisible(false);
            closeBtn.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            z = 0;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void newCustomerBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newCustomerBtnComponentShown
        // TODO add your handling code here:
            try{
                Thread.sleep(250);
                updateCustomerBtn.setVisible(true);
                jLabel2.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
    }//GEN-LAST:event_newCustomerBtnComponentShown

    private void updateCustomerBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updateCustomerBtnComponentShown
        // TODO add your handling code here:
                    try{
                Thread.sleep(250);
                customerDetailsBtn.setVisible(true);
                jLabel3.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_updateCustomerBtnComponentShown

    private void customerDetailsBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_customerDetailsBtnComponentShown
        // TODO add your handling code here:
                    try{
                Thread.sleep(250);
                deleteCustomerBtn.setVisible(true);
                jLabel4.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_customerDetailsBtnComponentShown

    private void deleteCustomerBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteCustomerBtnComponentShown
        // TODO add your handling code here:
                    try{
                Thread.sleep(250);
                newProductBtn.setVisible(true);
                jLabel5.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_deleteCustomerBtnComponentShown

    private void newProductBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newProductBtnComponentShown
        // TODO add your handling code here:
                    try{
                Thread.sleep(250);
                updateProductBtn.setVisible(true);
                jLabel6.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_newProductBtnComponentShown

    private void updateProductBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updateProductBtnComponentShown
        // TODO add your handling code here:
                    try{
                Thread.sleep(250);
                productDetailsbtn.setVisible(true);
                jLabel7.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
    }//GEN-LAST:event_updateProductBtnComponentShown

    private void productDetailsbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_productDetailsbtnComponentShown
        // TODO add your handling code here:
        
            try{
                Thread.sleep(250);
                deleteProductBtn.setVisible(true);
                jLabel8.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_productDetailsbtnComponentShown

    private void deleteProductBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteProductBtnComponentShown
        // TODO add your handling code here:
            try{
                Thread.sleep(250);
                salesBtn.setVisible(true);
                jLabel9.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_deleteProductBtnComponentShown

    private void salesBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_salesBtnComponentShown
        // TODO add your handling code here:
            try{
                Thread.sleep(250);
                logoutBtn.setVisible(true);
                jLabel10.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_salesBtnComponentShown

    private void logoutBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutBtnComponentShown
        // TODO add your handling code here:
            try{
                Thread.sleep(250);
                closeBtn.setVisible(true);
                jLabel11.setVisible(true);
            }
            catch(InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_logoutBtnComponentShown

    private void closeBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_closeBtnComponentShown
        // TODO add your handling code here:
        z = 1;
    }//GEN-LAST:event_closeBtnComponentShown

    private void updateCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerBtnActionPerformed
        // TODO add your handling code here:
        updatecustomer.setVisible(true);
    }//GEN-LAST:event_updateCustomerBtnActionPerformed

    private void customerDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDetailsBtnActionPerformed
        // TODO add your handling code here:
        customerdetails.setVisible(true);
    }//GEN-LAST:event_customerDetailsBtnActionPerformed

    private void deleteCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerBtnActionPerformed
        // TODO add your handling code here:
        deletecustomer.setVisible(true);
    }//GEN-LAST:event_deleteCustomerBtnActionPerformed

    private void newProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductBtnActionPerformed
        // TODO add your handling code here:
        newproduct.setVisible(true);
    }//GEN-LAST:event_newProductBtnActionPerformed

    private void updateProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductBtnActionPerformed
        // TODO add your handling code here:
        updateproduct.setVisible(true);
    }//GEN-LAST:event_updateProductBtnActionPerformed

    private void productDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDetailsbtnActionPerformed
        // TODO add your handling code here:
        productdetails.setVisible(true);
    }//GEN-LAST:event_productDetailsbtnActionPerformed

    private void deleteProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBtnActionPerformed
        // TODO add your handling code here:
        deleteproduct.setVisible(true);
    }//GEN-LAST:event_deleteProductBtnActionPerformed

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        // TODO add your handling code here:
        sales.setVisible(true);
    }//GEN-LAST:event_salesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton customerDetailsBtn;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JButton deleteProductBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton newCustomerBtn;
    private javax.swing.JButton newProductBtn;
    private javax.swing.JButton productDetailsbtn;
    private javax.swing.JButton salesBtn;
    private javax.swing.JButton updateCustomerBtn;
    private javax.swing.JButton updateProductBtn;
    // End of variables declaration//GEN-END:variables
}
